### ISSUE TITLE
[Alexis Camarasa](w5-project_visualizacion)

### ISSUE THREAD

**Issue by camarasa1987** [Ironhack-Data-Madrid-Abril-2023/w5-project_visualizacion#1]
https://github.com/camarasa1987/w5-project_visualizacion.git

**Comment by OrianAmpuero** [comment]
Muy bien Alexis! Sé que has estado trabajando fuerte en entender todas las herramientas de esta semana. En el caso del repo, considero que te falta más información, ya que en el readme solo está la explicación pero sin ninguna imagen y este proyecto sobre todo debería ser el más vistoso dado que es de visualización; además la redacción del readme trata de hacerla en un idioma (toda en inglés o toda en español). 
Entonces, trata de adjuntar imágenes del PowerBi para que las personas tengan una pincelada de lo que hay y luego si les interesa pues clonen tu repo ya que es la forma de verlo si no tienen link público.

**Comment by camarasa1987** [comment]
Entendido, gracias por el feed back!

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
