### ISSUE TITLE
[Luis Galdeano](w5-project_visualizacion)

### ISSUE THREAD

**Issue by LuisGaldeano** [Ironhack-Data-Madrid-Abril-2023/w5-project_visualizacion#10]
https://github.com/LuisGaldeano/Visualizacion-F1Statistics

**Comment by CharlyKill7** [comment]
Muy buen proyecto, Luis. Permíteme algunos comentarios:

- Respecto al repositorio, aunque en general está bastante bien, te recomiendo dos cosas: meter los archivos sueltos en carpetas y poner un título más explicativo. Aunque entiendo que la pregunta que lanzas es un buen gancho y que, además, el nombre del repo ya incluye las palabras visualización y F1, creo que queda más limpio darle, de nuevo, un título "más título" al readme. Y, por supuesto, la pregunta sería lo primero del cuerpo y, si hace falta, en negrita y en mayúsculas. Es decir, estoy de acuerdo en encabezar y darle importancia a la pregunta que detona tu historia, pero tal vez no en detrimento de quitar un título que resuma de qué va el proyecto: visualización de datos de Formula 1. 
- Precisamente, muy bien el storytelling. Queda claro todo el tiempo lo que buscas a cada paso y por qué visualizas lo que visualizas; sabes qué pregunta te dirige y eso es casi más importante que la visualización en sí. Finalmente ofreces una conclusión, y eso es importante. Sin embargo, me gustaría invitarte a continuar el proyecto en un futuro, teniendo en cuenta otros factores para comparar a los pilotos del pasado y del presente. Por ejemplo, no me quedo tranquilo viendo que Valteri Bottas, con las mismas vueltas aproximadas, arrasa en puntos a leyendas como Senna o Fittipaldi. El motivo de esto es una obviedad, pero quizá no lo sea tanto encontrar una forma de comparar la calidad real de los pilotos a través de los datos.
- La visualización, en mi opinión, está genial. Tal vez no hayas hecho los gráficos más innovadores o chulos pero, precisamente, considero que hay que primar la comunicación y la utilidad a los fuegos de artificio. En ese sentido, van de la mano tu historia y tu trabajo estadístico-visual. No se me ocurre mejor manera de hacerlo. 

En cuanto a la presentación del martes:

-	Mal exponer sentado, aunque sea más cómodo por el ordenador.
-	Bien empezar con lapregunta, así enganchas al público a tu historia.
-	Buen apoyo en lo visual para reforzar tus palabras.
-	Bien de tiempo.

En general, buen proyecto, Luis. Cuida los detalles, como las carpetas del repo, para que no desmerezcan un trabajo ciertamente riguroso. ¡Sigue así!
