### ISSUE TITLE
[Javier R.](w5-project_visualizacion)

### ISSUE THREAD

**Issue by jrodrisanz** [Ironhack-Data-Madrid-Abril-2023/w5-project_visualizacion#11]
https://github.com/jrodrisanz/Project_visualization

**Comment by CharlyKill7** [comment]
Buen proyecto, Javier. Permíteme algunos comentarios:

- En cuanto al repositorio, buen readme (queda claro de qué va el proyecto y lo que pretendes) y buena estructura de carpetas. Sin embargo, has incluido todo el proceso de ETL, desde los notebook de extracción y transformación hasta la carga en SQL. Este proyecto era de visualización y, por tanto, no deberías haber incluido el trabajo previo. Entiendo que te lo curraste, pero hay que aprender a enseñar lo que se debe enseñar, independientemente de lo que haya por detrás. Asimismo, mencionas en tu readme que has usado librerías como Matplotlib o Seaborn pero, corrígeme si me equivoco, los gráficos los has hecho en Tableau y no he visto que uses los de Python en ningún sitio. 
- En cuanto a la visualización, en general es correcta. Sin embargo, hay algunos gráficos menos explicativos que otros. Entiendo que hayas querido explorar diferentes opciones, pero ten en cuenta que lo primordial es que el receptor lo entienda bien y rápido. En ese sentido, visualizaciones como la de 'Pelis y Series por año', 'Top 10 Géneros' o el buscador de pelis están muy bien; de un vistazo queda claro qué generos copan las plataformas o de qué año son la mayoría de producciones. Sin embargo, otros como el de 'Valoración por género' o el de 'Distribución de Pelis y Series" requieren interactuar y pensar un poco más para entender lo que quieren decir. Incluso el mapa, aunque funciona, es una forma más complicada de entender de un vistazo que paises producen más contenido. Salvo Estados Unidos, claramente resaltado, por los colores del mapa parecen iguales Reino Unido y Marruecos, cuando el primero tiene casi 500 producciones y el segundo sólo 2. Una tabla ranking hubiera dado esa información más rápida y claramente.

En general, buen proyecto, Javier. Eso sí, echo en falta una conclusión, una respuesta a tu pregunta planteada: ¿qué plataforma tiene objetivamente mejor contenido? La verdad es que, tras ver tu dashboard, no tengo clara la respuesta. Dale una vuelta ;)

Pero, eh, sigue así, que se nota el curro y la mejora. 

¡Ánimo!
