### ISSUE TITLE
[Giotto](viz_data_gamer)

### ISSUE THREAD

**Issue by giottomillan** [Ironhack-Data-Madrid-Abril-2023/w5-project_visualizacion#12]
https://github.com/giottomillan/viz_data_gamer.git

**Comment by OrianAmpuero** [comment]
Bien Giotto!! El repo esta desarrollado correctamente aunque me gustaría ver más imágenes ya que de eso va el proyecto; así como en link del tableau que esté a la mano.
El dashboard esta bien, buena paleta de color elegida y sé que puedes ir sacando más cosas con la practica, así que te animo a seguir currando en ello.

En cuanto a la presentación:
- Buen inicio de presentación, es muy importante para captar la atención del público.
- No decir lo malo, ya que nadie lo sabe y queda mejor sacar lo bueno y vender lo que tienes. 
- Bien de tiempo.
