### ISSUE TITLE
[Eduardo Goicoechea] Visualisation Project

### ISSUE THREAD

**Issue by Hrodward88** [Ironhack-Data-Madrid-Abril-2023/w5-project_visualizacion#13]
https://github.com/Hrodward88/W5_Data_visualization.git

**Comment by OrianAmpuero** [comment]
Bien Eduardo!! El repo esta correcto respecto a la organización de los archivos y el desarrollo del readme, aunque sería mejor poner unos cuantos gráficos más que texto ya que el fin de este es básicamente visualizar.
En cuanto a ambos dashboards, sé que te lo has currado y que no te hace honor el link porque lo mueve todo (por eso es bueno tener a la mano esos pantallazos). Pero te tengo que decir que a veces poco es mejor ya que se puede entender mejor, la idea en general esta chula la verdad, la paleta de colores muy bien pero luego no se ve claro cada objetivo ni métrica. Cuesta saber que se está mostrando y te aconsejo ver ideas o plantillas para guiarse.
