### ISSUE TITLE
[Anton Utray](w5-project_visualizacion)

### ISSUE THREAD

**Issue by Anton-Utray** [Ironhack-Data-Madrid-Abril-2023/w5-project_visualizacion#14]
https://github.com/Anton-Utray/ETL-EDA

**Comment by OrianAmpuero** [comment]
Excelente trabajo Antón! En cuanto al repo, todo correcto y desarrollado con detalles, se nota el curro detrás y me dejas con pocas cosas de decirte más que espero con ansias tu proyecto final. 👏
