### ISSUE TITLE
[LORENZO IMIZCOZ](w5-project_visualizacion)

### ISSUE THREAD

**Issue by Lorensou** [Ironhack-Data-Madrid-Abril-2023/w5-project_visualizacion#15]
https://github.com/Lorensou/w5-project_visualizacion/tree/main

**Comment by CharlyKill7** [comment]
Buen proyecto, Lorenzo. Algunos comentarios:

- En cuanto al repositorio, está bien estructurado, con los archivos en carpetas y un readme de extensión correcta. Sin embargo, tengo un par de pegas. La ETL no era objeto de este proyecto y no hace falta que lo metas en el repo, sobre todo si es la misma que ya está en el proyecto de la semana pasada. Por otro lado, aunque tu readme explica bien dónde está cada cosa, en realidad carece de objetivo claro. En este proyecto había que practicar el storytelling, idealmente partiendo de una pregunta que se pretende resolver a través de la visualización de los datos. 
- Respecto a la visualización en sí, en general, buen trabajo. Los filtros funcionan bien y, según entiendo, tienes una página para filtrar información de eventos, otra para información de jugadores y una última con el gráfico de sunburst. No obstante, he echado de menos una mejor explicación, en algún sitio, de para qué sirve cada hoja. Yo lo he averiguado probando y pensando, y eso es más de lo que tal vez hará un jefe, en un futuro, cuando le presentes un proyecto. Intenta que sea muy explicativo. Por ejemplo, en la hoja de eventos, tienes altura y peso y, después de probar, he deducido que es la media de altura y peso de ese evento concreto, pero puede que de primeras no resulte tan evidente. Lo mismo sucede con el sunburst; aunque el gráfico está chulo y me alegro de que lo hayas hecho, puede que no sea el más intuitivo para el visitante profano. Tal vez un buen título o una pequeña leyenda podría ayudar en ese sentido.

En general, buen proyecto, Lorenzo. Las visualizaciones están bien y eso era lo más importante, pero recuerda que algo debe no sólo estar bien, también parecerlo y, cuanto antes, mejor. Las primeras frases de readme deben enganchar (por eso el storytelling) y los primeros vistazos al Dashboard no deben confundir (por eso los títulos o leyendas). Una vez consigues eso, tu trabajo es suficientemente bueno para hacer el resto. Vas mejorando y me alegro mucho, pero sé que puedes hacer todavía más, así que dale duro.

¡Ánimo!
