### ISSUE TITLE
[Juan Gouveia](w5-project_visualizacion)

### ISSUE THREAD

**Issue by JuanGouveia** [Ironhack-Data-Madrid-Abril-2023/w5-project_visualizacion#17]
https://github.com/JuanGouveia/Visualization-Project

**Comment by CharlyKill7** [comment]
Buen proyecto, Juan. Permíteme algunos comentarios:

- Bien en cuanto al repo. Cuidas del orden con las carpetas adecuadas y tu readme está bien estructurado y es bastante explicativo. Hay una cosa que te recomendaría tener en cuenta: cuando el visitante llega a tu repo y va leyendo, se encuentra con los diferentes gráficos que has hecho, pero no llega al enlace interactivo hasta el final. Es decir, no puede hacer mouseover sobre una barra para saber la información de tooltip. Por ejemplo, en el mapa sólo ves cinco paises del mismo color, y no sabes a qué marca corresponde. Para ello te recomiendaría darle una dimensión de color a cada marca ya en el primer gráfico de barras, para que así, durante todo tu análisis, quede claro de qué brand hablamos. Un poco lo mismo sucede con el de jugadores; tenlo en cuenta para el futuro. 
- Repecto a la visualización, es tecnicamente correcta. Como he comentado arriba, echo de menos algo más de color, esa dimensión extra tan visual. También te recomiendo subirlo como Historia en vez de como Dashboard a Tableau Public; de esta forma consigues unos botones que enlazan con todas las páginas de tu proyecto, y así si el visitante quiere ver más en detalle un visual concreto, puede hacerlo.

En cuanto a la presentación del martes:
-	Bien exponer de pie.
-	Un poco más de energía, de pasión, para que el público empatice contigo y se meta en tu historia (aunque entiendo que no era tu mejor día).
-	Buen apoyo visual en los gráficos, aunque no siempre queda claro por la velocidad a la que los comentas. 
-	Un poco corto, pero mejor eso que lo contrario.

En general, buen proyecto. Eso sí, intenta pensar un poco más desde la perspectiva del que ve tu Dashboard y no sabe nada. Puedes incluso preguntarle a alguien externo qué opina nada más verlo; estoy convencido de que verá cosas que tú no ves y, sobre todo, no verá otras que tú sí. Eso te vendrá genial. 

¡Ánimo!
