### ISSUE TITLE
"[joe sebastian]( w5-project_visualizacion)"

### ISSUE THREAD

**Issue by joeSL-ms** [Ironhack-Data-Madrid-Abril-2023/w5-project_visualizacion#18]
https://github.com/joeSL-ms/Visual/blob/main/README.md

**Comment by CharlyKill7** [comment]
Buen proyecto, Joe. Permíteme algunos comentarios:

- En cuanto al repo, te felicito por "esconder" aquello de lo que sé que estás más orgulloso. No es un proyecto de ETL y está bien que, si lo mencionas, lo ocultes en un desplegable. Sin embargo, te aconsejo organizar mejor los archivos en carpetas, porque solo tienes la de "cookies" y la de "selenium" que, precisamente, pertencen a la etapa de ETL. Intenta hacer una carpeta "data" para los "csv", otra "src" o "notebooks" para el código, etc. 
- En cuanto a la visualización, buen trabajo. Si tu objetivo era poder mostrar al publico los articulos disponibles desde 1999, está cumplido. Sin embargo, da la impresión de que algunas gráficas las haces porque hay que hacerlas, y no porque te generen un interés real. Por ejemplo, las barras de los autores por año y de los artículos por año son casi idénticas, lo cual es esperable aunque, probablemente, poco interesante. Noto que falta una historia, una pregunta que responder a través de tus datos visualizados. Supongo que no era tu objetivo pero, para el futuro, te recomiendo generar una especie de hilo argumental planteamiento-nudo-desenlace que enganche al visitante o espectador. En ese sentido, podrías haber analizado, por ejemplo, las variaciones del tipo de artículo (categoría) a través de los años, intentando responder a preguntas como: ¿Hacia dónde se encamina el interés de los artículos cientificos? 

En general, buen proyecto, Joe. Me parece muy interesante a nivel personal que construyas una herramienta como esta y te felicito por ello. Recuerda no obstante que aquí estás para practicar ciertas cosas, como en este caso era el EDA y el storytelling, y te aconsejo que intentes ceñirte, por el momento, a lo que te piden. No me cabe duda de que habrá tiempo para que desarrolles todas las ideas que tienes. ¡Ánimo con ello!
