### ISSUE TITLE
[Ignacio Romero][w5-project_visualizacion]

### ISSUE THREAD

**Issue by Linxx333** [Ironhack-Data-Madrid-Abril-2023/w5-project_visualizacion#19]
https://github.com/Linxx333/EDA-Colonized-Countries

**Comment by CharlyKill7** [comment]
Buen proyecto, Nacho. Voy a dividir en tres grandes partes el feedback:

1. Las visualizaciones: 
El trabajo en cuanto a Tableau y sus mapas, está muy bien. Sé que después de este proyecto los dominas y, a pesar de no conseguir lo de los filtros, sé cuánto te has pegado con ello. Además, no te conformaste con que el mapa saliera; cuestionaste los resultados no esperados y, en aras de ser fiel a la realidad, cambiaste el gradiente de color para resaltar China, por ejemplo. Eso denota preocupación por el dato y está genial. El único "pero" sería no haber podido profundizar en otro tipo de gráfico o tabla. Es una lástima, pero seguro que se dará en el futuro.

2. La exposición:
-	Bien exponer de pie.
-	Buen detalle el pasar por el discord el enlace.
-	Empezar con una pregunta funciona muy bien, bie hecho. Consigues implicar a la audiencia. 
-	Bien utilizado el humor, a cuentagotas. 
-	Buen apoyo en lo visual. Aunque me pregunto si no hubiera quedado mejor, para visualizar, por ejemplo, el índice de Gini por países más claramente, intercalar algún otro tipo de gráfico, como una pequeña tabla que dejara más claro el orden y, por otro lado, te sirviera para oxigenar un poco tanto mapa tras mapa.
-	Un poco largo, no obstante. Justo hacia el final creo que decaía un poco le interés. Pero, en general, una gran exposición.

3. El repo:
Aunque suelo empezar por aquí el feedback, lo he dejado para el final porque quería decirte primero cómo fue tu exposición. Gracias a ella entendí todo tu proyecto, me quedó claro lo que buscabas y lo que encontraste. Me atrapó tu historia y me la tragué con gusto hasta el final. Sin embargo, no creo que pueda decir lo mismo alguien que llegue hasta ella a través de tu readme. Tu análisis es demasiado escueto y, al tener en otro lado la visu, es dificil seguir el hilo de lo que dices siguiendo tus mapas. Tal vez hubiera sido bueno extenderte un poco en ese análisis y poner, si no quieres que quede muy extenso, los mapas en desplegables, al menos los más importantes. Te invito a que lo hagas para que la impresión de los reclutadores mejore.

Sigue trabajando así y, como llevo un tiempo diciéndote, intenta cuidar los detalles de forma para que no se pierda tu fondo.

¡Ánimo!
