### ISSUE TITLE
[Nerea Riveiro]( w5-project_visualizacion)

### ISSUE THREAD

**Issue by NereaRiveiro** [Ironhack-Data-Madrid-Abril-2023/w5-project_visualizacion#20]
https://github.com/NereaRiveiro/The-last-climb.git

**Comment by CharlyKill7** [comment]
Buen proyecto, Nerea. Algunos comentarios al respecto:

- En cuanto al repositorio, muy bien la estructura tanto de carpetas como del readme. Ya venías haciéndolo, así que simplemente sigue así y prueba maneras de mejorarlo todavía mas. Eso sí, cuidado con qué meter en cada carpeta. Por ejemplo, en la carpeta de dashboards tienes tres y sólo hace falta uno.
- A propósito del storytelling, bien realizado. Planteas varias preguntas de interés, respondidas en tus conclusiones tras atravesar tus visualizaciones. Como ya comentamos, hubiera estado bien contar con la cifra de ascensiones, e incluso con un desglose por nacionalidades, ya que estudias la relación de éstas con las muertes. He visto que lo indicas en las conclusiones (Annapurna, K2 y Nanga Parbat), pero aunque me fío de ti, mejor presentar en datos esa información. Así, por ejemplo, podrías sacar también qué porcentaje muere de cada nacionalidad por ascensión. Igual los que más mueren son los sherpas nepalíes, en volumen, pero tal vez en proporción mueran muy pocos por ascensión, dado que es su oficio y su tierra. 
- Las visualizaciones están muy bien. El mapa está bien centrado y es muy claro; también los dashboards, que no están sobrecargados y ofrecen información clara y útil. Un detalle: cuando usas el filtro de montañas, para ver datos especificos de una concreta, me gusta mucho la idea del mapa en la esquina superior derecha. Sin embargo, aparece tan centrado en el punto que no puedes hacerte una idea de su localización sin hacer zoom. Igual es un tema de versiones pero, si puedes, intenta corregirlo porque me parece una característica que mola. 

En general, buen proyecto. Te has ceñido a lo que se pedía: repo, EDA, storytelling y visualización están bien ejecutadas. Siempre se puede hacer más, y te animo a que lo intentes. Sé que puedes ir todavía más allá y me gustaría verlo. 

¡Ánimo!
