### ISSUE TITLE
[Juan Nuñez](w5-proyecto_visualizacion)

### ISSUE THREAD

**Issue by pizornpy** [Ironhack-Data-Madrid-Abril-2023/w5-project_visualizacion#21]

**Comment by pizornpy** [comment]
https://github.com/pizornpy/Proyecto-Visualizaci-n

**Comment by CharlyKill7** [comment]
Buen proyecto, Juan, aunque tengo sensaciones encontradas. En este proyecto voy dando feedback por partes: primero el repo, después la visualización y, finalmente, la historia. En tu caso voy a hacer una excepción y te voy a dar mi impresión general.

A mí me gusta tu idea. A nivel personal, he aprendido mucho estudiando tu figura y leyendo tu texto, además de buscando info extra por mi cuenta. Después de ese pequeño estudio y, sin ser demasiado estricto, creo que tiene sentido lo que construyes, y que refleja correctamente lo que quieres transmitir. Es díficil representar en una pequeña figura 3D la inmensidad del pensamiento filosófico desde Platón a Hegel, por lo que me parece que has encontrado una buena forma de hacerlo. También valoro la originalidad, y esa visualización no la ha hecho nadie más en clase; tampoco hay otro proyecto sin datos numéricos. Por todo ello, te felicito.

Sin embargo, te planteo mis dudas. Para poder entender correctamente tu figura, he tenido que, literalmente, ponerme a estudiar. La idea de hacer una visualización es la de simplificar y, aunque desde cierta perspectiva lo has hecho, creo que no tiene nada de simple para el visitante medio de tu repo. Cuando tienes datos complejos como Data Analyst, y los tienes que resumir y hacer comprensibles para un tercero (presumiblemente, un jefe o cliente), cuanto más obvia sea la figura, mejor. Por otro lado, este proyecto tenía como objetivo probar distintas maneras de visualizar, y me quedo un poco frío con una única figura, por dificil que sea. Tu proyecto en una celda de notebook. Quizá podrías haber hecho más visualizaciones, mucho más sencillas, que sirvieran como introducción para situar ideas y autores; tal vez una línea temporal sencilla. Y que tu figura llegara como la estrella, como una especie de megafigura final que todo lo resume. Así, habrías preparado al visitante/oyente para entenderla y valorarla mucho más.

Ya te lo dije en SQL: no te quedes en la superficie. Intenta darle vueltas a cómo será la impresión de quien tendrás enfrente, al margen de lo que tú entiendas o te guste. Puede que así hubieras añadido un colchón previo que habría convertido tu proyecto en algo excelente. Espero que cojas esos consejos y los plasmes, sobre todo, en el proyecto final. Me gusta cómo piensas y me da rabia que se diluya ese pensamiento por la falta de ejecución. Pero tú puedes. Y yo, quiero verlo.

¡Dale duro!
