### ISSUE TITLE
[Jesus Guardia Ramirez] (w5-project_visualizacion)

### ISSUE THREAD

**Issue by JesusGuardiaRamirez** [Ironhack-Data-Madrid-Abril-2023/w5-project_visualizacion#22]
https://github.com/JesusGuardiaRamirez/Proyecto_dashboard

**Comment by CharlyKill7** [comment]
Proyecto correcto, Jesús. Permíteme algunos comentarios:

- En cuanto al repo, varias cosas. No hace falta que hables de la ETL porque este proyecto no consistía en ese. Si quieres ponerlo, utiliza un desplegable HTML para ocultarlo y que lo vean sólo si les interesa. También te recomiendo poner los .csv en una carpeta "data" o similar, para que quede más organizado el repo. Y hablando de los .csv, he observado que muchos terminan en .csv.csv, imagino que igual por cómo los nombras cuando los exportas con pd.read_csv. Échale un ojo. Y, un detalle más de forma que de fondo, te aconsejo no poner etcéteras cuando enumeres puntos o pasos.
- Respecto a la visualización, en general, bien realizada. SIn embargo, echo de menos algunas cosas, como que ajustes mejor los títulos de los gráficos (quitándole el "Sum of") o des más información sobre los KPIs que das. Me refiero a los 2M de denuncias o los 393 huérfanos; no queda claro a qué periodo corresponde. Precisamente, si te fijas en los datos de huérfanos que tienes en tus tablas, entre 2003 y 2012 todas las filas son '0' y, en mi opinión, seguro que hubo algún huérfano en esos años. Seguramente los datos están incompletos, por lo que te recomiendo que quites esas filas antes de visualizar ese dato.

En general, buen proyecto, Jesús, pero intenta prestar atención al detalle, ponerte en la piel de quien visita tu readme sin ninguna información previa y preguntarte si se está transmitiendo bien lo que tú quieres que reciba. En todo caso, mucha suerte con el proyecto final, que temas como éste son importantes y merecen la pena los proyectos que le dan relieve. 

¡Ánimo!

**Comment by CharlyKill7** [comment]
Olvidé darte feedback de la exposición:

-	Mejor exponer de pie que sentado, aunque sea más cómodo por el ordenador.
-	Sube el tono de voz si puedes, para captar mejor la atención del público. Algo más de pasión es recomendable para que empaticen contigo y “compren” tu historia. 
-	Poco apoyo visual en tus gráficas.
-	Muy corto, apenas dos minutos
