### ISSUE TITLE
[Carlos Clemente](w5-project_visualizacion)

### ISSUE THREAD

**Issue by Carlosclementegarcia** [Ironhack-Data-Madrid-Abril-2023/w5-project_visualizacion#3]

**Comment by Carlosclementegarcia** [comment]
https://github.com/Carlosclementegarcia/w5-project_visualizacion.git

**Comment by OrianAmpuero** [comment]
Muy bien Carlos, se notan los avances y el curro detrás de este proyecto. Has aplicado diferentes funcionalidades para poder filtrar y encontrar información necesaria a cualquier empresa con los datos que tenias. Recuerda poner todos los archivos en carpetas para mejor organización y quizás un video o más imágenes del dashboard filtrado para que alguien que no sepa nada tenga más idea al entrar al repo.

Ya espero ver tu proyecto final y ánimo en la última recta.

**Comment by Carlosclementegarcia** [comment]
Muchas gracias por tus comentarios.
Sigo esforzándome

**Comment by OrianAmpuero** [comment]
Carlos! En cuanto a la presentación, me faltó darte feedback:
- Buen inicio e introducción del proyecto
- Trata de no dar la espalda
- Solo mostrar la visualización ya que ese era el único fin
- Bien de tiempo
