### ISSUE TITLE
[David Aparicio] (w5-project_visualizacion)

### ISSUE THREAD

**Issue by dapafer** [Ironhack-Data-Madrid-Abril-2023/w5-project_visualizacion#4]
https://github.com/dapafer/visualization-project

**Comment by OrianAmpuero** [comment]
Muy bien David! El repo esta correcto en cuanto al desarrollo de contenido y visualización, así como a la organización de las carpetas; como punto de mejora te diría que el link de tableau lo pongas mas a la mano porque es confuso llegar y la idea es que este a la mano. 
En el dashboard, muy bien elegido la paleta de colores pero a la hora de gráficos se puede perder mucha info y no es muy estético, así que la idea es poner menos pero mas vistoso, es decir, si hay gráficos que no te dicen a primera vista lo que hay pues mejor busca otro o mostrar esos datos de otra forma.
De resto muy bien y ya espero con ansias tu proyecto final!! 👏
