### ISSUE TITLE
[Jose Luis Reguera Alvarez](w5-project_visualizacion)

### ISSUE THREAD

**Issue by jose-luis666** [Ironhack-Data-Madrid-Abril-2023/w5-project_visualizacion#5]
https://github.com/jose-luis666/proyecto_dashboard

**Comment by CharlyKill7** [comment]
Muy buen proyecto, Celu 😜

- En cuanto al repo, buen trabajo. Lo tienes organizado en carpetas y el readme es muy explicativo (tal vez demasiado, pero a mí me gusta). Tal vez hubiera estado bien lanzar una pregunta más concreta como objeto de tu análisis, para que generes una historia tipo planteamiento-nudo-desenlace, que pueda enganchar más a tu dashboard al visitante o espectador. No obstante, se nota el curro de documentación que le has metido y eso está genial.
- Respecto a la visualización, mi enhorabuena. Se nota que está trabajado, sin perder de vista la sencillez que debe sentir quien entra al Dashboard. Muchas veces queremos hacer muchos y variados gráficos y termina resultando contraproducente. En tu caso,  el gráfico de años es muy explicativo a primera vista, igual que el de proporción de Pelis/Series. También el filtro está muy bien y, al presentarlo como historia, he podido probarlo (ya es más de lo que me ha dado la mayoría). Como único detalle, el mapa, aunque entiendo que lo hagas, es poco explicativo de primeras, porque obliga a recorrer los paises para ver cúanto se produce en cada uno. Sin embargo, si hubieras puesto una simple tabla, hubiera quedado claro de un vistazo dónde se produce más. Intenta pensar siempre en alguien externo que no sabe nada; ¿cómo vería ese visitante tu Dashboard sin más contexto? ¿Cuánto tardaría en entender cada visualización? Tal vez eso te ayude a decidir cómo y qué visualizar.

En general, muy buen proyecto. El paso de las semanas te está sentando bien, así que no puedo más que darte ánimos y decirte que sigas así.

¡Ánimo!
