### ISSUE TITLE
[Augusto Abad Varela](4_IRONHACK_Visualization)

### ISSUE THREAD

**Issue by gusavato** [Ironhack-Data-Madrid-Abril-2023/w5-project_visualizacion#6]
https://github.com/gusavato/4_IRONHACK_Visualization

**Comment by OrianAmpuero** [comment]
Excelente trabajo Gus! Se nota la evolución desde el repo, con el desarrollo del readme y la organización de archivos, así como los detalles de código, visualización y demás. 

Ten cuidado con los links del 'ETL_Tracks.ipynb' y 'ETL_fest.ipynb' porque cuando haces click te saca del notebook, son cositas para que las corrijan en lo que puedas.

De resto, tengo pocas oportunidades de mejora, más bien felicitarte y decirte que me parece un currazo, ya solo espero ver tu proyecto final.
