### ISSUE TITLE
['Daniel VIllanueva']['Proyect_Dashboard']

### ISSUE THREAD

**Issue by DFDA19** [Ironhack-Data-Madrid-Abril-2023/w5-project_visualizacion#7]
https://github.com/DFDA19/Proyect_Dashboard

**Comment by OrianAmpuero** [comment]
Bien Daniel! En cuanto al repo ten cuidado con los errores ortográficos y de redacción (Storytelling...), así como los detalles de Markdown que se te puede escapar algún detalle como # de más. Si es un proyecto de visualización lo ideal sería ver más gráficos en el desarrollo del readme y coloca el link a la mano para que sea más fácil llegar a él.

Por otra parte, el dashboard esta bien pero si es poco intuitivo y también algo lioso; hay que intentar mostrar las datos de la forma más clara, usando filtros o dividendo datos; en fin, hay diversas formas de mejorar la manera en que se ve la información, así que te animo a seguir practicando porque este punto es importante.

A seguir trabajando a tope que ya estamos en la recta final!
