### ISSUE TITLE
[Carlos Palomares]( w5-project_visualizacion)

### ISSUE THREAD

**Issue by CarlosPalomaresGarcia** [Ironhack-Data-Madrid-Abril-2023/w5-project_visualizacion#8]
https://github.com/CarlosPalomaresGarcia/Project5.Data_Visualization.git

**Comment by OrianAmpuero** [comment]
Bien Carlos, se van notando los avances de todo lo aprendido. Sé que has currado en cuanto a conocer las diferentes herramientas para visualizar pero quizás me hizo falta ver más gráficos y más detalles estéticos para que fuese agradable a la vista o llamativo, ya que se trata de 'enamorar' a primera vista y entender claramente lo que hay.
