### ISSUE TITLE
[Carolina Rivera](w5-project_visualizacion)

### ISSUE THREAD

**Issue by carolinariveraa** [Ironhack-Data-Madrid-Abril-2023/w5-project_visualizacion#9]
https://github.com/carolinariveraa/EDA_NYPD

**Comment by OrianAmpuero** [comment]
Excelente proyecto Caro, se ve el curro desde el readme hasta el código. En este caso que se trataba de visualización, he de decir que has hecho un gran trabajo, demostrando en detalle cada análisis y haciéndolo agradable a la vista; se entienden los datos con solo ver los Dashboards  y me dejas con pocas oportunidades de mejora ya que me parece muy buen trabajo en todos los sentidos. Solo apuntar que cuidado con los commits ya que se quedan puestos en tu repo y depende de quien los vea puede dar risa o no jajaja.
Ansiosa de tu proyecto final, ánimo!! 👏
